name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    name: windows release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: compile and release
        run: cd installer && cargo build --release --locked
