name: Release

on:
  release:
    types:
      - created

jobs:
  build:
    name: windows release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: update version
        run: rustup install stable
      - name: compile and release
        run: cd installer && cargo build --release --locked
