name: Build and Upload Release

on:
  release:
    types:
      - created

jobs:
  build:
    name: windows release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Configure
        run: rustup target add x86_64-pc-windows-gnu
      - name: Compile
        run: cd installer && cargo build -- target x86_64-pc-windows-gnu